{
 "title": "Traces",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device ID",
    "query": "SELECT device_id FROM customer.my_devices ORDER BY device_id;"
   }
  ]
 },
 "panels": [
  {
   "title": "x",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  sample_dt AS time,\n  x\nFROM\n  customer.device_accel_sample_pt\nWHERE\n  $__timeFilter(sample_dt)\n  AND device_id = '$device_id'\nORDER BY\n  sample_dt;"
    }
   ]
  },
  {
   "title": "y",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  sample_dt AS time,\n  y\nFROM\n  customer.device_accel_sample_pt\nWHERE\n  $__timeFilter(sample_dt)\n  AND device_id = '$device_id'\nORDER BY\n  sample_dt;"
    }
   ]
  },
  {
   "title": "z",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  sample_dt AS time,\n  z\nFROM\n  customer.device_accel_sample_pt\nWHERE\n  $__timeFilter(sample_dt)\n  AND device_id = '$device_id'\nORDER BY\n  sample_dt;"
    }
   ]
  }
 ]
}